// <auto-generated />
using HwStore.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HwStore.Persistence.Migrations
{
    [DbContext(typeof(HwStoreDbContext))]
    [Migration("20220619154054_AddingSpecification")]
    partial class AddingSpecification
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HwStore.Domain.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Amd"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Intel"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Nvidia"
                        },
                        new
                        {
                            Id = 4,
                            Name = "CorsAir"
                        });
                });

            modelBuilder.Entity("HwStore.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Cpu",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ram",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Vga",
                            ParentCategoryId = 1
                        });
                });

            modelBuilder.Entity("HwStore.Domain.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("HwStore.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            CategoryId = 3,
                            Description = "Get the ultimate game changer. AMD Radeon™ RX 6800 XT graphics card features breakthrough AMD RDNA™ 2 architecture. ",
                            Name = "6800XT",
                            Price = 800m,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 1,
                            CategoryId = 3,
                            Description = "Get the ultimate game changer. AMD Radeon™ RX 6700 XT graphics card features breakthrough AMD RDNA™ 2 architecture. ",
                            Name = "6700XT",
                            Price = 700m,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 3,
                            CategoryId = 3,
                            Description = "The GeForce RTX™ 3070 is powered by Ampere—NVIDIA's 2nd gen RTX architecture.",
                            Name = "RTX 3070",
                            Price = 850m,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 2,
                            CategoryId = 1,
                            Description = "AMD Ryzen 7 5800X - Ryzen 7 5000 Series Vermeer (Zen 3) 8-Core 3.8 GHz Socket AM4 105W Desktop Processor ",
                            Name = "Ryzen 7 5800X",
                            Price = 500m,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 1,
                            CategoryId = 1,
                            Description = "AMD Ryzen 7 5700X - Ryzen 7 5000 Series Vermeer (Zen 3) 8-Core 3.4 GHz Socket AM4 105W Desktop Processor -",
                            Name = "Ryzen 7 5700X",
                            Price = 400m,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 2,
                            CategoryId = 1,
                            Description = "Intel Core i7-12700K - Core i7 12th Gen Alder Lake 12-Core (8P+4E) 3.6 GHz LGA 1700 125W Intel UHD Graphics 770",
                            Name = "12700K",
                            Price = 450m,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 2,
                            CategoryId = 1,
                            Description = "Intel Core i9-11900K - Core i9 11th Gen Rocket Lake 8-Core 3.5 GHz LGA 1200 125W Intel UHD Graphics 750 Desktop Processor ",
                            Name = "11900K",
                            Price = 450m,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 4,
                            CategoryId = 2,
                            Description = "Vengeance RGB Pro 16GB (2 x 8GB) Timing: 16-18-18-36  ",
                            Name = "Vengeance RGB Pro",
                            Price = 100m,
                            Quantity = 10
                        });
                });

            modelBuilder.Entity("HwStore.Domain.Specification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("SpecLabel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("productId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("productId");

                    b.ToTable("Specifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SpecLabel = "INTERFACE",
                            SpecValue = "PCI Express® Gen 4",
                            productId = 1
                        },
                        new
                        {
                            Id = 2,
                            SpecLabel = "CORES",
                            SpecValue = "4608 Units",
                            productId = 1
                        },
                        new
                        {
                            Id = 3,
                            SpecLabel = "CORE CLOCKS",
                            SpecValue = "Boost: Up to 2310 MHz / Game: Up to 2065 MHz",
                            productId = 1
                        },
                        new
                        {
                            Id = 4,
                            SpecLabel = "MEMORY SPEED",
                            SpecValue = "16 Gbps",
                            productId = 1
                        },
                        new
                        {
                            Id = 5,
                            SpecLabel = "MEMORY ",
                            SpecValue = "16GB GDDR6",
                            productId = 1
                        },
                        new
                        {
                            Id = 6,
                            SpecLabel = "MEMORY BUS",
                            SpecValue = "256-bit",
                            productId = 1
                        },
                        new
                        {
                            Id = 7,
                            SpecLabel = "OUTPUT",
                            SpecValue = "DisplayPort x 3 (v1.4)",
                            productId = 1
                        },
                        new
                        {
                            Id = 8,
                            SpecLabel = "POWER CONNECTORS",
                            SpecValue = "300 W",
                            productId = 1
                        },
                        new
                        {
                            Id = 9,
                            SpecLabel = "INTERFACE",
                            SpecValue = "PCI Express® Gen 4",
                            productId = 2
                        },
                        new
                        {
                            Id = 10,
                            SpecLabel = "CORES",
                            SpecValue = "2560 Units",
                            productId = 2
                        },
                        new
                        {
                            Id = 11,
                            SpecLabel = "CORE CLOCKS",
                            SpecValue = "Boost: Up to 2620 MHz / Game: Up to 2474 MHz",
                            productId = 2
                        },
                        new
                        {
                            Id = 12,
                            SpecLabel = "MEMORY SPEED",
                            SpecValue = "16 Gbps",
                            productId = 2
                        },
                        new
                        {
                            Id = 13,
                            SpecLabel = "MEMORY ",
                            SpecValue = "12GB GDDR6",
                            productId = 2
                        },
                        new
                        {
                            Id = 14,
                            SpecLabel = "MEMORY BUS",
                            SpecValue = "192-bit",
                            productId = 2
                        },
                        new
                        {
                            Id = 15,
                            SpecLabel = "OUTPUT",
                            SpecValue = "DisplayPort x 3 (v1.4)",
                            productId = 2
                        },
                        new
                        {
                            Id = 16,
                            SpecLabel = "POWER CONNECTORS",
                            SpecValue = "230 W",
                            productId = 3
                        },
                        new
                        {
                            Id = 17,
                            SpecLabel = "INTERFACE",
                            SpecValue = "PCI Express® Gen 4",
                            productId = 3
                        },
                        new
                        {
                            Id = 18,
                            SpecLabel = "CORES",
                            SpecValue = "5888 Units",
                            productId = 3
                        },
                        new
                        {
                            Id = 19,
                            SpecLabel = "CORE CLOCKS",
                            SpecValue = "Boost:Boost: 1845 MHz",
                            productId = 3
                        },
                        new
                        {
                            Id = 20,
                            SpecLabel = "MEMORY SPEED",
                            SpecValue = "14 Gbps",
                            productId = 3
                        },
                        new
                        {
                            Id = 21,
                            SpecLabel = "MEMORY ",
                            SpecValue = "8GB GDDR6",
                            productId = 3
                        },
                        new
                        {
                            Id = 22,
                            SpecLabel = "MEMORY BUS",
                            SpecValue = "256-bit",
                            productId = 3
                        },
                        new
                        {
                            Id = 23,
                            SpecLabel = "OUTPUT",
                            SpecValue = "DisplayPort x 3 (v1.4) / HDMI x 1 (Supports 4K@120Hz as specified in HDMI 2.1)",
                            productId = 3
                        },
                        new
                        {
                            Id = 24,
                            SpecLabel = "POWER CONNECTORS",
                            SpecValue = "240W",
                            productId = 3
                        },
                        new
                        {
                            Id = 25,
                            SpecLabel = "Series",
                            SpecValue = "Ryzen 7 5000 Series",
                            productId = 4
                        },
                        new
                        {
                            Id = 26,
                            SpecLabel = "CPU Socket Type ",
                            SpecValue = "Socket AM4",
                            productId = 4
                        },
                        new
                        {
                            Id = 27,
                            SpecLabel = "# of Cores ",
                            SpecValue = "8-Core",
                            productId = 4
                        },
                        new
                        {
                            Id = 28,
                            SpecLabel = "# of Threads ",
                            SpecValue = "16",
                            productId = 4
                        },
                        new
                        {
                            Id = 29,
                            SpecLabel = "Operating Frequency  ",
                            SpecValue = "3.8 GHz",
                            productId = 4
                        },
                        new
                        {
                            Id = 30,
                            SpecLabel = "Max Turbo Frequency ",
                            SpecValue = "4.7 GHz",
                            productId = 4
                        },
                        new
                        {
                            Id = 31,
                            SpecLabel = "L2 Cache ",
                            SpecValue = "4MB",
                            productId = 4
                        },
                        new
                        {
                            Id = 32,
                            SpecLabel = "L3 Cache ",
                            SpecValue = "32MB",
                            productId = 4
                        },
                        new
                        {
                            Id = 33,
                            SpecLabel = "Manufacturing Tech ",
                            SpecValue = "7nm",
                            productId = 4
                        },
                        new
                        {
                            Id = 34,
                            SpecLabel = "Memory Types",
                            SpecValue = "DDR4 3200",
                            productId = 4
                        },
                        new
                        {
                            Id = 35,
                            SpecLabel = "Thermal Design Power ",
                            SpecValue = "105W",
                            productId = 4
                        },
                        new
                        {
                            Id = 36,
                            SpecLabel = "Series",
                            SpecValue = "Ryzen 7 5000 Series",
                            productId = 5
                        },
                        new
                        {
                            Id = 79,
                            SpecLabel = "CPU Socket Type ",
                            SpecValue = "Socket AM4",
                            productId = 5
                        },
                        new
                        {
                            Id = 37,
                            SpecLabel = "# of Cores ",
                            SpecValue = "8-Core",
                            productId = 5
                        },
                        new
                        {
                            Id = 38,
                            SpecLabel = "# of Threads ",
                            SpecValue = "16",
                            productId = 5
                        },
                        new
                        {
                            Id = 39,
                            SpecLabel = "Operating Frequency  ",
                            SpecValue = "3.3 GHz",
                            productId = 5
                        },
                        new
                        {
                            Id = 40,
                            SpecLabel = "Max Turbo Frequency ",
                            SpecValue = "4.3 GHz",
                            productId = 5
                        },
                        new
                        {
                            Id = 41,
                            SpecLabel = "L2 Cache ",
                            SpecValue = "4MB",
                            productId = 5
                        },
                        new
                        {
                            Id = 42,
                            SpecLabel = "L3 Cache ",
                            SpecValue = "32MB",
                            productId = 5
                        },
                        new
                        {
                            Id = 43,
                            SpecLabel = "Manufacturing Tech ",
                            SpecValue = "7nm",
                            productId = 5
                        },
                        new
                        {
                            Id = 44,
                            SpecLabel = "Memory Types",
                            SpecValue = "DDR4 3200",
                            productId = 5
                        },
                        new
                        {
                            Id = 45,
                            SpecLabel = "Thermal Design Power ",
                            SpecValue = "105W",
                            productId = 5
                        },
                        new
                        {
                            Id = 46,
                            SpecLabel = "Series",
                            SpecValue = "Core i7 12th Gen",
                            productId = 6
                        },
                        new
                        {
                            Id = 47,
                            SpecLabel = "CPU Socket Type",
                            SpecValue = "LGA 1700",
                            productId = 6
                        },
                        new
                        {
                            Id = 48,
                            SpecLabel = "Core Name",
                            SpecValue = "Alder Lake",
                            productId = 6
                        },
                        new
                        {
                            Id = 49,
                            SpecLabel = "# of Cores ",
                            SpecValue = "12-Core (8P+4E)",
                            productId = 6
                        },
                        new
                        {
                            Id = 50,
                            SpecLabel = "# of Threads ",
                            SpecValue = "20",
                            productId = 6
                        },
                        new
                        {
                            Id = 51,
                            SpecLabel = "Operating Frequency  ",
                            SpecValue = "3.6 GHz",
                            productId = 6
                        },
                        new
                        {
                            Id = 52,
                            SpecLabel = "Max Turbo Frequency ",
                            SpecValue = "Up to 4.9 GHz",
                            productId = 6
                        },
                        new
                        {
                            Id = 53,
                            SpecLabel = "L2 Cache ",
                            SpecValue = "12MB",
                            productId = 6
                        },
                        new
                        {
                            Id = 54,
                            SpecLabel = "L3 Cache ",
                            SpecValue = "25MB",
                            productId = 6
                        },
                        new
                        {
                            Id = 55,
                            SpecLabel = "Manufacturing Tech ",
                            SpecValue = "Intel 7",
                            productId = 6
                        },
                        new
                        {
                            Id = 56,
                            SpecLabel = "Memory Types",
                            SpecValue = "DDR4 3200 / DDR5 4800",
                            productId = 6
                        },
                        new
                        {
                            Id = 57,
                            SpecLabel = "Thermal Design Power ",
                            SpecValue = "190W",
                            productId = 6
                        },
                        new
                        {
                            Id = 58,
                            SpecLabel = "Series",
                            SpecValue = "Core i7 11th Gen",
                            productId = 7
                        },
                        new
                        {
                            Id = 59,
                            SpecLabel = "CPU Socket Type",
                            SpecValue = "LGA 1700",
                            productId = 7
                        },
                        new
                        {
                            Id = 60,
                            SpecLabel = "Core Name",
                            SpecValue = "Alder Lake",
                            productId = 7
                        },
                        new
                        {
                            Id = 61,
                            SpecLabel = "# of Cores ",
                            SpecValue = "12-Core",
                            productId = 7
                        },
                        new
                        {
                            Id = 62,
                            SpecLabel = "# of Threads ",
                            SpecValue = "24",
                            productId = 7
                        },
                        new
                        {
                            Id = 63,
                            SpecLabel = "Operating Frequency  ",
                            SpecValue = "3.6 GHz",
                            productId = 7
                        },
                        new
                        {
                            Id = 64,
                            SpecLabel = "Max Turbo Frequency ",
                            SpecValue = "Up to 4.9 GHz",
                            productId = 7
                        },
                        new
                        {
                            Id = 65,
                            SpecLabel = "L2 Cache ",
                            SpecValue = "12MB",
                            productId = 7
                        },
                        new
                        {
                            Id = 66,
                            SpecLabel = "L3 Cache ",
                            SpecValue = "25MB",
                            productId = 7
                        },
                        new
                        {
                            Id = 67,
                            SpecLabel = "Manufacturing Tech ",
                            SpecValue = "Intel 7",
                            productId = 7
                        },
                        new
                        {
                            Id = 68,
                            SpecLabel = "Memory Types",
                            SpecValue = "DDR4 3200 ",
                            productId = 7
                        },
                        new
                        {
                            Id = 69,
                            SpecLabel = "Thermal Design Power ",
                            SpecValue = "190W",
                            productId = 7
                        },
                        new
                        {
                            Id = 70,
                            SpecLabel = "Capacity",
                            SpecValue = "16GB (2 x 8GB)",
                            productId = 8
                        },
                        new
                        {
                            Id = 71,
                            SpecLabel = "Type",
                            SpecValue = "288-Pin DDR4 SDRAM",
                            productId = 8
                        },
                        new
                        {
                            Id = 72,
                            SpecLabel = "Speed ",
                            SpecValue = "DDR4 3200 (PC4 25600)",
                            productId = 8
                        },
                        new
                        {
                            Id = 73,
                            SpecLabel = "CAS Latency ",
                            SpecValue = "16",
                            productId = 8
                        },
                        new
                        {
                            Id = 74,
                            SpecLabel = "Timing",
                            SpecValue = "16-18-18-36",
                            productId = 8
                        },
                        new
                        {
                            Id = 75,
                            SpecLabel = "Voltage ",
                            SpecValue = "1.35V",
                            productId = 8
                        },
                        new
                        {
                            Id = 76,
                            SpecLabel = "Chipset",
                            SpecValue = "Intel XMP 2.0",
                            productId = 8
                        },
                        new
                        {
                            Id = 77,
                            SpecLabel = "Color",
                            SpecValue = "Black",
                            productId = 8
                        },
                        new
                        {
                            Id = 78,
                            SpecLabel = "Heat Spreader",
                            SpecValue = "Anodized Aluminum",
                            productId = 8
                        });
                });

            modelBuilder.Entity("HwStore.Domain.Image", b =>
                {
                    b.HasOne("HwStore.Domain.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("HwStore.Domain.Product", b =>
                {
                    b.HasOne("HwStore.Domain.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HwStore.Domain.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("HwStore.Domain.Specification", b =>
                {
                    b.HasOne("HwStore.Domain.Product", "Product")
                        .WithMany("Specifications")
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("HwStore.Domain.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("HwStore.Domain.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("HwStore.Domain.Product", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Specifications");
                });
#pragma warning restore 612, 618
        }
    }
}
